### ISSUE TITLE
One server or two?

### ISSUE THREAD

**Issue by gbob81** [capnmidnight/Calla#114]
I'm trying to install Calla and am running into issues, so I'm re-reading the instructions and am having trouble figuring out whether I need to two servers (one for Jitsi and one for Calla) or just one server? Based on this...

```
Make sure you keep the distinction between your Jitsi installation and your Calla installation clear. You can conceivably run them on the same server, but I won't be digging into customizing a Jitsi installation enough to figure that out, so my setup has them on separate servers.
```
...I'd say it was two servers, but then when I read the instructions it looks like they're living on the same server, e.g.

```

Edit the jitsi docker-compose.yml to add the following service section:

  services:
      # Calla
      calla:
          image: nginx:alpine
          volumes:
              - ${CONFIG}/Calla/js:/usr/share/nginx/html
          command: sh /usr/share/nginx/html/entrypoint.sh
```

Should I have them on the same server or separate servers? Also is there a way to install Calla other than using Docker?
