### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by mooomooo** [capnmidnight/Calla#95]
Is it possible to build and run this locally without ASP.NET?  If so, how? 

In the meantime, I'm trying to just `npm run build` -- is there a reason why resonance-audio is handled by a git submodule, while soundr is handled by libman?  Instead of both being handled the same way, e.g. by npm dependencies?

**Comment by fredrik-lindseth** [comment]
I'm joining in under this issue, some clarification on the build instructions would be useful. I'm confused on how to build Calla too. I did the following

```
git clone https://github.com/capnmidnight/Calla.git
git submodule init
git submodule update
```

I then opened the solution in Vistual Studio and tried to build but got this 

```
Calla-Site.csproj: [NU1105] Unable to find project information for 'C:\dev\workspace\Calla\Juniper\src\Juniper.Server\Juniper.Server.csproj'. 
If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.
```

And now I'm not sure how to fix this. I have a `Calla-Site`-project and a `Juniper.Root` in the solution, but no `Juniper` or `Juniper.Server`

**Comment by capnmidnight** [comment]
Hi folks,

Apologies. I've been playing fast and loose with my repos lately for my project at work (a VR project which uses Calla under the hood). I'll be removing the Juniper, SignalR, and ASP.NET dependencies soon.

The resonance-audio dependency is a git submodule because I had to fork Resonance (and its dependency, Omnitone) to fix several egregious defects that Google left in them when they basically abandoned the projects two, three years ago.

**Comment by puddyput** [comment]
I've set up a Calla installation using one of the first commits in this repo, before the asp.net changes.
This is the change I've used:
https://github.com/capnmidnight/Calla/tree/13a90e97b48deedaaa947cd0e6fb01d7bd82f251

This is what I added to the jitsi docker-compose:

```
    # Calla
    calla:
        image: nginx:alpine
        volumes:
            - ${CONFIG}/Calla/Calla-Site/wwwroot:/usr/share/nginx/html
        ports:
            - '8282:80'
        environment:
            - JITSI_HOST=localhost
            - JVB_HOST=meet.jitsi
            - JVB_MUC=muc.meet.jitsi
# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
```

Of course this is not the latest version and does not have all the features as the current one, but I didn't want to have to mess around with asp.net :)
